// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/metrics/metrics.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Метрика
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Ответы
type MetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MetricsBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsBatchRequest) Reset() {
	*x = MetricsBatchRequest{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsBatchRequest) ProtoMessage() {}

func (x *MetricsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsBatchRequest.ProtoReflect.Descriptor instead.
func (*MetricsBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsBatchRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricsBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsBatchResponse) Reset() {
	*x = MetricsBatchResponse{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsBatchResponse) ProtoMessage() {}

func (x *MetricsBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsBatchResponse.ProtoReflect.Descriptor instead.
func (*MetricsBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricsBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_metrics_metrics_proto protoreflect.FileDescriptor

const file_proto_metrics_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/metrics/metrics.proto\x12\ametrics\"X\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"@\n" +
	"\x0eMetricResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"@\n" +
	"\x13MetricsBatchRequest\x12)\n" +
	"\ametrics\x18\x01 \x03(\v2\x0f.metrics.MetricR\ametrics\"F\n" +
	"\x14MetricsBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x9b\x01\n" +
	"\x0eMetricsService\x127\n" +
	"\vStoreMetric\x12\x0f.metrics.Metric\x1a\x17.metrics.MetricResponse\x12P\n" +
	"\x11StoreMetricsBatch\x12\x1c.metrics.MetricsBatchRequest\x1a\x1d.metrics.MetricsBatchResponseBAZ?github.com/ruslanDantsov/osmetrics-server/proto/metrics;metricsb\x06proto3"

var (
	file_proto_metrics_metrics_proto_rawDescOnce sync.Once
	file_proto_metrics_metrics_proto_rawDescData []byte
)

func file_proto_metrics_metrics_proto_rawDescGZIP() []byte {
	file_proto_metrics_metrics_proto_rawDescOnce.Do(func() {
		file_proto_metrics_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_metrics_proto_rawDesc), len(file_proto_metrics_metrics_proto_rawDesc)))
	})
	return file_proto_metrics_metrics_proto_rawDescData
}

var file_proto_metrics_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_metrics_metrics_proto_goTypes = []any{
	(*Metric)(nil),               // 0: metrics.Metric
	(*MetricResponse)(nil),       // 1: metrics.MetricResponse
	(*MetricsBatchRequest)(nil),  // 2: metrics.MetricsBatchRequest
	(*MetricsBatchResponse)(nil), // 3: metrics.MetricsBatchResponse
}
var file_proto_metrics_metrics_proto_depIdxs = []int32{
	0, // 0: metrics.MetricsBatchRequest.metrics:type_name -> metrics.Metric
	0, // 1: metrics.MetricsService.StoreMetric:input_type -> metrics.Metric
	2, // 2: metrics.MetricsService.StoreMetricsBatch:input_type -> metrics.MetricsBatchRequest
	1, // 3: metrics.MetricsService.StoreMetric:output_type -> metrics.MetricResponse
	3, // 4: metrics.MetricsService.StoreMetricsBatch:output_type -> metrics.MetricsBatchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_metrics_metrics_proto_init() }
func file_proto_metrics_metrics_proto_init() {
	if File_proto_metrics_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_metrics_proto_rawDesc), len(file_proto_metrics_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metrics_metrics_proto_goTypes,
		DependencyIndexes: file_proto_metrics_metrics_proto_depIdxs,
		MessageInfos:      file_proto_metrics_metrics_proto_msgTypes,
	}.Build()
	File_proto_metrics_metrics_proto = out.File
	file_proto_metrics_metrics_proto_goTypes = nil
	file_proto_metrics_metrics_proto_depIdxs = nil
}
